repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude:
        ".xml"

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    - id: check-manifest

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.7
    hooks:
    - id: pylint
      args:
        - --disable=missing-docstring,similarities,fixme,bad-continuation
      additional_dependencies:
        - sphinx
        - docutils
        - pygments
      exclude: >
        (?x)^(
          setup.py|
          tests/.*|
          docs/.*
        )$
